# Generated by Django 2.2.5 on 2020-09-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_methode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_methode',
            new_name='login_method',
        ),
    ]
